### ISSUE TITLE
Error on Heroku

### ISSUE THREAD

**Issue by timscott** [rainchen/react-rails-img#1]
When I deploy to Heroku, I get an error on precompile. I'm on Rails 4.2.6.

```
NameError: undefined local variable or method `assets' for #<#<Class:0x007f54b175b5b8>:0x007f54b3151a80>
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/react-rails-img-0.1.1/vendor/assets/javascripts/react_rails_img.js.jsx.erb:7:in `_evaluate_template'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/erb_processor.rb:26:in `call'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/erb_processor.rb:13:in `call'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/bundle.rb:23:in `block in call'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/utils.rb:183:in `dfs'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/bundle.rb:24:in `call'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/base.rb:66:in `find_asset'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:142:in `block in find'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:225:in `block in stat_tree'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `each'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `stat_directory'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:224:in `stat_tree'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `each'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `each'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:140:in `find'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:168:in `compile'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-3.5.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/tmp/build_c50582c052e79a3fae965f9521516a50/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
```

**Comment by rainchen** [comment]
@timscott I will setup a heroku app to check this issue.

**Comment by itai-sagi** [comment]
also happens when running rake assets:precompile RAILS_ENV=production
PR to amend: https://github.com/rainchen/react-rails-img/pull/2

**Comment by rainchen** [comment]
fixed in this PR https://github.com/rainchen/react-rails-img/pull/3
